"/":
  controller: Pages
  action: default

"/creation_de_compte":
  controller: Users
  action: add

"/connexion":
  controller: Users
  action: login

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword


"/liste_des_utilisateurs":
  controller: Users
  action: default
